// automatically generated by the FlatBuffers compiler, do not modify

package guideme.flatbuffers.scene;

import java.nio.ByteBuffer;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

@SuppressWarnings("unused")
public final class ExpAnimatedTexturePartFrame extends Struct {

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public ExpAnimatedTexturePartFrame __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public int index() {
        return bb.getShort(bb_pos + 0) & 0xFFFF;
    }

    public void mutateIndex(int index) {
        bb.putShort(bb_pos + 0, (short) index);
    }

    public int time() {
        return bb.getShort(bb_pos + 2) & 0xFFFF;
    }

    public void mutateTime(int time) {
        bb.putShort(bb_pos + 2, (short) time);
    }

    public static int createExpAnimatedTexturePartFrame(FlatBufferBuilder builder, int index, int time) {
        builder.prep(2, 4);
        builder.putShort((short) time);
        builder.putShort((short) index);
        return builder.offset();
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public ExpAnimatedTexturePartFrame get(int j) {
            return get(new ExpAnimatedTexturePartFrame(), j);
        }

        public ExpAnimatedTexturePartFrame get(ExpAnimatedTexturePartFrame obj, int j) {
            return obj.__assign(__element(j), bb);
        }
    }
}
